<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\AppIcon.ico" />
    <None Remove="Images\page_delete.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\AppIcon.ico" />
    <Resource Include="Images\page_delete.png" />
  </ItemGroup>

</Project>
