CREATE TABLE IF NOT EXISTS Profiles
	(
	Id INTEGER NOT NULL PRIMARY KEY,
  Profession TEXT NOT NULL,
  Biography TEXT NOT NULL,
  PersonId INTEGER NOT NULL,
  FOREIGN KEY("PersonId") REFERENCES "Persons" ON DELETE CASCADE
  );