<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Caliburn.Micro" Version="5.0.258" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Styles.Library\Styles.Library.csproj" />
    <ProjectReference Include="..\Utilities.Library\Utilities.Library.csproj" />
  </ItemGroup>

</Project>
